### ISSUE TITLE
disabled form option does not work with custom templates

### ISSUE THREAD

**Issue by istarkov** [gcanti/tcomb-form#161]
example:
```javascript
import React, { Component, PropTypes } from 'react';
import cx from 'classnames';
import t, { form } from 'tcomb-form';
import * as semantic from 'tcomb-form/lib/templates/semantic';

const { Form } = form;
Form.templates = semantic;

const Item = t.struct({
  name: t.Str,
});

const formLayout = (locals) => {
  const {
    disabled,
    inputs: { name }} = locals;

  const disabledClass = cx('field', {disabled});

  return (
    <form className={cx('ui form')}>
      <h4 className="ui dividing header">Item Information</h4>
      <div className={disabledClass}>
        <label>Name</label>
        {name}
      </div>
    </form>
  );
};

const itemOptions = {
  auto: 'none',
  template: formLayout
};


export default class ItemForm extends Component {
  render() {
    const {id, fetchItemStatus, item} = this.props;

    const options = {
      disabled: true
    };

    return (
      <Form
        ref="form"
        type={Item}
        value={item}
        options={{...itemOptions, ...options}}
      />
    );
  }
}
```

The `name` field at `formLayout` is drawn as disabled (i set `disabledClass = cx('field', {disabled});`)
but is editable. And all works fine without custom template.

The question is, how i can set disabled properties to children inside `formLayout`.
(as i see disabled is not a `prop` of `locals.inputs` elements)

**Comment by istarkov** [comment]
Looks like cloning elements with options i need  works

This `formLayout` works as expected

```javascript
const formLayout = (locals) => {
  const {
    disabled,
    inputs: { name }} = locals;

  const disabledClass = cx('field', {disabled});

  return (
    <form className={cx('ui form')}>
      <h4 className="ui dividing header">Item Information</h4>
      <div className={disabledClass}>
        <label>Name</label>
        {React.cloneElement(name, {options: {disabled}})}
      </div>
    </form>
  );
};
```

Is it official way to set disabled property?

**Comment by gcanti** [comment]
Hi!

1) If you want to use the semantic skin it's better to import tcomb-form from `lib`:

https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#changing-the-default-skin

```js
import t, { form } from 'tcomb-form/lib';
import en from 'tcomb-form/lib/i18n/en';
import * as semantic from 'tcomb-form/lib/templates/semantic';

const { Form } = form;

Form.i18n = en;
Form.templates = semantic;
```

Otherwise you are also importing the bootstrap skin (the default one).

2) You can disable field by field:

```js
const Item = t.struct({
  name: t.Str,
  surname: t.Str // <- another field to show the concept
});

const itemOptions = {
  auto: 'none',
  template: formLayout,
  fields: {
    name: {
      disabled: true // <- name will be disabled (surname will be enabled)
    }
  }
};
``` 

another way would be to disable all the fields at the struct level:

```js
const itemOptions = {
  auto: 'none',
  template: formLayout,
  disabled: true // <- disable both name and surname
};
```

Now the problem is how to implement this last feature in semantic. In my skin I chose to use a fieldset:

https://github.com/gcanti/tcomb-form/blob/master/src/templates/semantic.js#L601

as a wrapper in order to exploit its capability to disable all the contained inputs with only one attribute:

https://github.com/gcanti/tcomb-form/blob/master/src/templates/semantic.js#L603

If you write a custom template for your struct you have to handle this by your own, for example using the same trick:

```js
const formLayout = (locals) => {
  const {
    disabled,
    inputs: { name }} = locals;

  const disabledClass = cx('field', {disabled});

  return (
    <form className={cx('ui form')}>
      <fieldset disabled={disabled}> // <- handle disabled attribute
        <h4 className="ui dividing header">Item Information</h4>
        <div className={disabledClass}>
          <label>Name</label>
          {name}
        </div>
      </fieldset>
    </form>
  );
};
```

**Beware**. Fieldset styling seems not officially supported by semantic (weird)

https://github.com/Semantic-Org/Semantic-UI/issues/596

**Comment by istarkov** [comment]
Thank you!!!
I forgot about `fieldset tag` can have `disabled` attrubute.
