### ISSUE TITLE
Pass events to inputs

### ISSUE THREAD

**Issue by cranesandcaff** [gcanti/tcomb-form#53]
There is currently no way to pass events from the configuration to the input. If you want to watch/act on specific fields you're SOL.

I was working with different ways to do so but they caused focus loss, if I find a solution I'll put a pull request in, could you point me in the right direction?

**Comment by cranesandcaff** [comment]
After reading https://github.com/gcanti/tcomb-form/issues/51 it looks like events may not be included in the scope? I'd be willing to try my hand at adding them with some direction for how you would prefer the API to work?

**Comment by gcanti** [comment]
> If you want to watch/act on specific fields...how you would prefer the API to work

Sure, since I'm refactoring it's a good time to examine new features: what kind of events you'd like to have? Could you show me an example?

**Comment by cranesandcaff** [comment]
I'd assume/prefer I guess that all browser events, onBlur, onChange, etc were passed. 

Unless there is a reason not to just pass the props down that I'm not thinking of?

**Comment by gcanti** [comment]
> Could you show me an example?

A real use case would help me a lot to understand the problem, find the best solution or point you in the right direction.

Anyway, since structures could be deeply nested, if you want all browser events the only API I can think of right now is a generic `events` object in `options` (I'd prefer to not list them explicity, it would be cumbersome), something like:

```js
// tcomb-form v0.4 API

var type = t.struct({
  name: t.Str,
  surname: t.Str
});

var options = {
  fields: {
    name: {
      events: {
        blur: function () {},
        keydown: function () {},
        ...
      }
    },
    surname: {
      events: {
        blur: function () {},
        keydown: function () {},
        ...
      }
    }
  }
};

<Form type={type} options={options} />
```

Notes:

- the `change` event should be reserved for tcomb-form internals
- some events have no meaning or are weird for some components

**Comment by astjohn** [comment]
Something like what @gcanti has proposed would be fantastic. Right now I would like to check for a wide-variety of events. Off the top of my head, blur for validation related feedback, keyup for hard returns skipping to the next field or automatically submitting the form and so on.
