### ISSUE TITLE
reading docs and sample, it's not clear that getValue will add the has-error class to fields 

### ISSUE THREAD

**Issue by ioRekz** [gcanti/tcomb-form#77]
I spent some time figuring this how you highlighted the errors on forms.
I didn't find anything in the doc or samples. 
I also did not expect that "getValue" would have side effects like this.

So maybe you can point me to the doc I missed so I feel dumb or consider adding this somewhere.
thanks, amazing work, so useful for me.

**Comment by gcanti** [comment]
Hi!
to understand the internals of tcomb-form, the best resource is the "Customizations" section. In particular these two subsections:

**Templates**

https://gcanti.github.io/tcomb-form/guide/index.html#templates

```
...
hasError: maybe(Bool),    // if true should show an error state
...
```

**Custom components**

https://gcanti.github.io/tcomb-form/guide/index.html#custom-components

> The custom component must have a getValue() method returning a ResultValidation instance

and the following example `SearchComponent`.

(The Bootstrap skin is nothing but a series of templates grouped together. Since in Bootstrap the standard way
to show an error state is adding a `has-error` class, I implemented that behaviour in my templates)
