### ISSUE TITLE
Support min/max for number type

### ISSUE THREAD

**Issue by Firfi** [gcanti/tcomb-form#91]
I can pass type: number as options for textbox (btw it is still type="text" by default though model has a Num type!) but can't pass min/max as these properties are ignored. I think problem is more 'global' as just adding min/max to Textbox.js (where 'type' is being handled, see `type: opts.type || 'text',`) wouldn't be sufficient as there's much more html5 attributes to consider. Thoughts?

**Comment by gcanti** [comment]
Hi,
validations should be left to tcomb-form through a type (a subtype in this case):

```
var MyNum = t.subtype(t.Num, function (n) {
  return n >= min && n <= max;
});
```

Regarding the (html5) attributes, after several requests and issues I'm considering a new version of tcomb-form that would allow to specify almost every attribute / event.

**Comment by Firfi** [comment]
Hey,

validations isn't an issue, I'm more concerned about how browser represents it (i.e. it draws type=number input with plus-minus arrows and minus arrow doesn't change number less than min). Thanks anyway.

**Comment by gcanti** [comment]
Sure, just saying that, with respect to the original goal of tcomb-form, using the provided validation capabilities allows a cross browser solution (in my use case I must support old browsers).

I know it's important to support new attributes / features (e.g. html5), I'm committed to write a new version.
Alas probably there will be breaking changes, so a v0.5 (see the new milestone)

**Comment by gcanti** [comment]
Hi @Firfi, just commited v0.5-alpha on master (if you want to give it a spin).
You'll be able to add any attributes:

```js
// example
var Type = t.struct({
  age: t.Num
});

var options = {
  fields: {
    age: {
      type: 'number',
      attrs: {
        min: 0,
        max: 5
      }
    }
  }
};
```

**Comment by Firfi** [comment]
Thanks @gcanti for this fix and for your great libraries. 

FYI I currently use it in my client's project to have same validation code on frontend and backend, and so far it fits great to my needs. As I use Meteorjs for my backend, I had to make some **build** changes in my fork, adjusting it to Meteorjs packaging system. Don't want to bother you with it's hacks (there's some inconvenient things to remember) so won't pull request it at least yet. If you want it though let me know.

**Comment by gcanti** [comment]
Hi, thanks for your feedback: I'm glad they are useful.

**Beware: v0.5 is still in flux!** 

These days I'm back-porting some v0.5 concepts to v0.4: Once finished this task I'll try to stabilize
v0.5 adding some new feature of v0.4 (namely a Datetime component, some bug fixes and, hopefully, a new skin for semantic ui).

I've tried to keep the breaking changes of v0.5 at the minimum:

- drop support for React v0.12
- all components extend a base `Component` class (means a (minor) breaking change for custom factories since the context is changed a little bit)
- new `attr` option (means a breaking change for `name`, `id` options, etc.. but the advantages should be **huge**: free attributes (like `min` and `max`) and events)
- (I'm not sure the `config` options will be still useful, I must think about it...)

Since you seems to already use v0.5, may I ask you if you find the new API handy? Have you some
suggestions to improve it?

**Comment by Firfi** [comment]
Actually, I did not noticed API change at all (my current forms use your old (?)), so I had a chance only to check attrs for min/max. Also tried placeholder attribute there but it seems it should be on another level right now (in field options itself) so some clear documentation about that could be useful. 

What I really craving for is 2 features, and both seems to be related to tcomb-validation: 1) is validation based on another struct values, i.e. on some siblings of current validated value (I.e. I have form with password and password confirmation; currently I just execute it in logic and set hasError). Maybe you already have it and I just didn't looked sharply.  2) is returning error message from validation. I have one library that I wrote just for proof-of-concept purpose, where I return only arrays from my validation methods. If array is not empty then validation failed and array itself contains validation info (paths and error messages). I find it pretty convenient.

**Comment by gcanti** [comment]
> Actually, I did not noticed API change at all (my current forms use your old (?)), so I had a chance only to check attrs for min/max. Also tried placeholder attribute there but it seems it should be on another level right now (in field options itself) so some clear documentation about that could be useful.

Sure. Once stabilized I absolutely must find the time to update the docs (alas it's really time comsuming).

> 1) is validation based on another struct values, i.e. on some siblings of current validated value (I.e. I have form with password and password confirmation; currently I just execute it in logic and set hasError). Maybe you already have it and I just didn't looked sharply

Usually I use a `subtype` (http://gcanti.github.io/tcomb/guide/index.html#subtype):

```js
function samePasswords(x) {
  return x.password === x.confirmPassword;
}

var Type = t.subtype(t.struct({
 password: t.Str,
 confirmPassword: t.Str
}), samePasswords);

var options = {
  error: function (value) { // http://gcanti.github.io/tcomb-form/guide/index.html#fieldset-error
    if (!samePasswords(value)) {
      return 'Password must be the same';
    }
  },
  fields: {
    password: {type: 'password'},
    confirmPassword: {type: 'password'}
  }
};

var App = React.createClass({

  save() {
    var validationResult = this.refs.form.getValue(true); // <- passing true here you get the raw `ValidationResult`
    console.log(validationResult); // print all errors
    if (validationResult.isValid()) {
      // ok
    }
  },

  render() {

    return (
      <div>
        <Form ref="form"
          type={Type}
          options={options}
        />
        <button className="btn btn-primary" onClick={this.save}>Save</button>
      </div>
    );
  }

});
```

> 2) is returning error message from validation. I have one library that I wrote just for proof-of-concept purpose, where I return only arrays from my validation methods. If array is not empty then validation failed and array itself contains validation info (paths and error messages). I find it pretty convenient.

If you pass the `true` param to `Form.getValue` you get the raw `ValidationResult` containing the array of errors (and paths)

http://gcanti.github.io/tcomb-form/guide/index.html#api-Form

(see the above snippet)

Is what you need?

**Comment by Firfi** [comment]
2) Not exactly. Currently I do it that way, but it's too much boilerplate code to write (i.e. call the getValue(true), check if it has errors, then set error state for inputs). I don't exclude possibility to move it into mixin but it feels like some feature that should be there out of the box and work like default getValue(), highlighting non-valid values. 

Another thing that is counterintuitive for me is setting error messages in options. Sometimes, I don't want component to know anything of it's forms error messages, and moving it in your validation method _looks_ like a logical way, i.e.

`return t.SomeClassForValidationResult(x.password === x.confirmPassword, 'Passwords should match')`

or even for subclass you mentioned in 1) 

```
return t.SomeClassForValidationResult(x.password === x.confirmPassword, {passwordConfirmation: 'Password should match'})
```

when user doesn't want show error state for `password` field but only for `passwordConfirmation` one.

This piece of information seems fit really well to (optionally) place it in validation method, otherwise this 'passwords should match' information being scattered in two places.

About 1) - that exactly what I overlooked in docs. Thanks!

**Comment by gcanti** [comment]
I see. The problem is that subtypes are very powerful but, since they are implemented with a predicate, they are opaque.

For example in your case, when the 2 passwords don't match the validation fails but I can't detect why programmatically (without an hint by the developer).

Giving a solution out of the box is a two edged sword: I learned that in the UI field, everyone has different
use cases and wants different UX solutions (one global error message, or an error message for each field, or an error message on a specific field, etc...).
So I chose to keep tcomb-form "low level" and provide just a configurable `option` object.

Your proposal is good, but what about nested types: say you have a struct with a nested list of structs and the validation fails due to a subtype condition on two deep fields?

I know my choice can lead to more boilerplate but as you suggest (mixins), if you can come up with a convention in your specific use case, you should be able to reduce the boilerplate.

Anyway I'm not entirely satisfied by the `error` and `hasError` options. Since v0.5 will break compatibility, I'll think about it: maybe there is a better trade off.

Thanks again for your feedback,

Giulio
